apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mysql-secret
data:
  MYSQL_ROOT_PASSWORD: "12345"
  MYSQL_DATABASE: testemed
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10 # Espera 10s para finalizar o container
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
      containers:
        - name: mysql
          image: mysql:8
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: mysql-secret
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage # binds with the persistent volume that is using the same storageClassName
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: "/mnt/mysql"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-dump
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mysql-dump
              image: leonardosartorello/mysqldump:v4
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          envFrom:
            - secretRef:
                name: secret-batch
          volumes:
            - name: mysql-storage
              persistentVolumeClaim:
                claimName: mysql-pvc
          volumeMounts:
            - name: mysqldump
              hostPath: path:/home/alura/mysqldump
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-batch
type: Opaque
stringData:
  MYSQL_ENV_DB_USER: root
  MYSQL_ENV_DB_PASS: "12345"
  MYSQL_ENV_DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_DATABASE: testemed
